<h2><center>Препроцессинг</center></h2>

### Препроцессинг 
([С использованием материалов Э.С. Клышинского](https://github.com/klyshinsky/ML_masters_2020/blob/master/Lecture_20201013_text_processing.ipynb))

* Токенизация - выделение абзацев, предложений, токенов
* Морфологический анализ (стемминг, лемматизация)
* Синтаксический анализ - определение связей между словами (деревья зависимостей) или синтаксически связанных групп слов (деревья составляющих)


Поиграем с [файлом с новостями](https://github.com/klyshinsky/ML_masters_2020/blob/master/data/lenta2018_summer2.txt) с сайта http://lenta.ru/. Все новости отделены друг от друга пятью знаками равно, дальше идет дата новости, пять минусов, текст новости.

Начнем с того, что загрузим новости в DataFrame.

In [1]:
import re
from tqdm import tqdm
import pandas as pd

import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (12, 8)

In [8]:
with open("/content/lenta", encoding="utf-8") as newsfile:
    text_news = [(n.split("-----\n")[0].split('\n')[0], 
                  n.split("-----\n")[0].split('\n')[1], 
                  n.split("-----\n")[1]) for n in newsfile.read().split("=====\n")[1:]]
    news = pd.DataFrame(text_news, columns = ['Header', 'Date', 'News'])

In [10]:
!head /content/lenta


=====
«Королева дерьмовых роботов» перенесла операцию на мозге
2018/06/01
-----
Шведская YouTube-знаменитость Симона Герц (Simone Giertz), прославившаяся необычными изобретениями, перенесла операцию. Об этом рассказали ее представители в Twitter. Еще в конце апреля девушка сообщила подписчикам о недуге. Оказалось, что у нее в мозге обнаружили доброкачественную опухоль размером с мяч для гольфа. Блогер даже дала ей имя, назвав новообразование Брайаном.  Герц сильно переживала перед хирургическим вмешательством. В одном из предоперационных видео она говорила, что очень напугана. Однако врачи быстро удалили опухоль и спасли девушке жизнь. «Симона вышла из хирургии, и ее врачи очень довольны тем, как все прошло. Она проспала достаточно долго, чтобы сделать неуместную шутку, так что все хорошо», — говорится на ее странице в Twitter.  27-летняя изобретательница из Стокгольма прославилась несколько лет назад, показывая подписчикам свои бесполезные изобретения. Например, Герц демонстрировала 

In [11]:
news.head()

Header  ...                                               News
0  «Королева дерьмовых роботов» перенесла операци...  ...  Шведская YouTube-знаменитость Симона Герц (Sim...
1                     У Су-57 нашли «тайные ноу-хау»  ...  Перспективный российский многофункциональный и...
2                    Знарок лишился еще одного поста  ...  Санкт-петербургский клуб Континентальной хокке...
3  СК заинтересовался задержанием аутиста московс...  ...  Следственный комитет по Москве начал проверку ...
4  Киевляне перекрыли проспект из-за сбитого поли...  ...  Более 100 жителей Киева перекрыли проспект Гри...

[5 rows x 3 columns]

Посмотрим, какие слова чаще всего встречаются в новостях. 

Разделим текст на слова простейшим образом, с помощью регулярных выражений: будем считать, что слово - это много русских или латинских букв.

In [13]:
words = re.findall('[A-Za-zА-ЯЁа-яё]+-[A-Za-zА-ЯЁа-яё]+|[A-Za-zА-ЯЁа-яё]+', news.News.iloc[0])
words

['Шведская',
 'YouTube-знаменитость',
 'Симона',
 'Герц',
 'Simone',
 'Giertz',
 'прославившаяся',
 'необычными',
 'изобретениями',
 'перенесла',
 'операцию',
 'Об',
 'этом',
 'рассказали',
 'ее',
 'представители',
 'в',
 'Twitter',
 'Еще',
 'в',
 'конце',
 'апреля',
 'девушка',
 'сообщила',
 'подписчикам',
 'о',
 'недуге',
 'Оказалось',
 'что',
 'у',
 'нее',
 'в',
 'мозге',
 'обнаружили',
 'доброкачественную',
 'опухоль',
 'размером',
 'с',
 'мяч',
 'для',
 'гольфа',
 'Блогер',
 'даже',
 'дала',
 'ей',
 'имя',
 'назвав',
 'новообразование',
 'Брайаном',
 'Герц',
 'сильно',
 'переживала',
 'перед',
 'хирургическим',
 'вмешательством',
 'В',
 'одном',
 'из',
 'предоперационных',
 'видео',
 'она',
 'говорила',
 'что',
 'очень',
 'напугана',
 'Однако',
 'врачи',
 'быстро',
 'удалили',
 'опухоль',
 'и',
 'спасли',
 'девушке',
 'жизнь',
 'Симона',
 'вышла',
 'из',
 'хирургии',
 'и',
 'ее',
 'врачи',
 'очень',
 'довольны',
 'тем',
 'как',
 'все',
 'прошло',
 'Она',
 'проспала',
 'достаточно'

Посчитаем частотность слов при помощи Counter.

In [14]:
from collections import Counter 

wdict = Counter(words) 
print(wdict)
print({w:n for w,n in wdict.items() if n>1})

Counter({'в': 5, 'Герц': 4, 'ее': 4, 'что': 3, 'из': 3, 'Симона': 2, 'Twitter': 2, 'девушка': 2, 'подписчикам': 2, 'опухоль': 2, 'с': 2, 'для': 2, 'очень': 2, 'врачи': 2, 'и': 2, 'все': 2, 'на': 2, 'Шведская': 1, 'YouTube-знаменитость': 1, 'Simone': 1, 'Giertz': 1, 'прославившаяся': 1, 'необычными': 1, 'изобретениями': 1, 'перенесла': 1, 'операцию': 1, 'Об': 1, 'этом': 1, 'рассказали': 1, 'представители': 1, 'Еще': 1, 'конце': 1, 'апреля': 1, 'сообщила': 1, 'о': 1, 'недуге': 1, 'Оказалось': 1, 'у': 1, 'нее': 1, 'мозге': 1, 'обнаружили': 1, 'доброкачественную': 1, 'размером': 1, 'мяч': 1, 'гольфа': 1, 'Блогер': 1, 'даже': 1, 'дала': 1, 'ей': 1, 'имя': 1, 'назвав': 1, 'новообразование': 1, 'Брайаном': 1, 'сильно': 1, 'переживала': 1, 'перед': 1, 'хирургическим': 1, 'вмешательством': 1, 'В': 1, 'одном': 1, 'предоперационных': 1, 'видео': 1, 'она': 1, 'говорила': 1, 'напугана': 1, 'Однако': 1, 'быстро': 1, 'удалили': 1, 'спасли': 1, 'девушке': 1, 'жизнь': 1, 'вышла': 1, 'хирургии': 1, 'дов

Фактически, выше мы провели преобразование текста в вектор. Пространство вектора определено на словаре текста - количество измерений совпадает с количеством слов, каждому измерению сопоставлено какое-то слово и отложена его частота. Подобный подход называют мешком слов (Bag of Words, BoW), так как все слова перемешиваются, их порядок больше не соблюдается, а сами слова сваливаются в один "мешок".

Обратите внимание на распределение частот в отдельных словах и парах. Такое распределение называется [распределением Ципфа](https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%BA%D0%BE%D0%BD_%D0%A6%D0%B8%D0%BF%D1%84%D0%B0) и является характерным практически для любого распределения частот слов и их комбинаций в текстах на любом естественном языке.

Для расчета частот существует CountVectorizer:

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
counter = CountVectorizer()
# Просим посчитать частоты слов.
res = counter.fit_transform([news.News.iloc[0]])
# Разреженное представление счетчика.
print(res[0,:10]) # По идентификатору можно получить частоту слова.
# Можно получить индекс по слову, ...
print('герц', counter.vocabulary_.get('герц'))
# ... но не наоборот.
print(counter.vocabulary_.get(18))
print(counter.vocabulary_) # Словарь, который сопоставляет слову его идентификатор.

  (0, 4)	1
  (0, 2)	1
  (0, 1)	1
  (0, 3)	2
  (0, 6)	1
  (0, 8)	1
  (0, 0)	1
  (0, 7)	1
  (0, 5)	1
  (0, 9)	1
герц 18
None
{'шведская': 123, 'youtube': 4, 'знаменитость': 37, 'симона': 104, 'герц': 18, 'simone': 2, 'giertz': 1, 'прославившаяся': 89, 'необычными': 66, 'изобретениями': 42, 'перенесла': 81, 'операцию': 76, 'об': 70, 'этом': 125, 'рассказали': 94, 'ее': 33, 'представители': 87, 'twitter': 3, 'еще': 35, 'конце': 46, 'апреля': 6, 'девушка': 24, 'сообщила': 106, 'подписчикам': 83, 'недуге': 64, 'оказалось': 74, 'что': 121, 'нее': 65, 'мозге': 54, 'обнаружили': 71, 'доброкачественную': 29, 'опухоль': 77, 'размером': 93, 'мяч': 56, 'для': 28, 'гольфа': 21, 'блогер': 8, 'даже': 22, 'дала': 23, 'ей': 34, 'имя': 43, 'назвав': 59, 'новообразование': 69, 'брайаном': 10, 'сильно': 103, 'переживала': 80, 'перед': 79, 'хирургическим': 117, 'вмешательством': 14, 'одном': 73, 'из': 38, 'предоперационных': 86, 'видео': 13, 'она': 75, 'говорила': 19, 'очень': 78, 'напугана': 63, 'однако': 

На вход классу подается список текстов. Результатом работы является [разреженная матрица](https://docs.scipy.org/doc/scipy/reference/sparse.html) частот слов. Если мы возьмем большое количество текстов, то в каждом из них встречается не так много разных слов, но словарь всех текстов вместе будет огромен. Обработка текстов должна вестись в едином пространстве. Пусть это будет пространство словаря всех текстов. Получается, что для текста с маленьким словарем мы должны хранить большое число нулей. Для того, чтобы этого избежать, хранят, например, один раз номер строки, индексы ненулевых значений и сами значения, то есть чуть больше двух чисел на ненулевое значение. Если считать, что словарь одного текста - 100 слов, а словарь всех текстов - 100 000 слов, мы получаем экономию места в 500 раз.

[Иллюстрация BOW](https://livebook.manning.com/book/natural-language-processing-in-action/chapter-4/v-4/61)

Обратите внимание, что все слова приведены к маленьким буквам, но про слова с дефисом этот класс ничего не знает.

Чтобы исправить эту ситуацию можно передать собственное регулярное выражение для разделения на слова.

In [26]:
counter=CountVectorizer(token_pattern=r'[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+')
# Обратите внимание, передается список текстов.
res=counter.fit_transform([news.News.iloc[0]])
print(counter.vocabulary_) 

{'шведская': 127, 'youtube-знаменитость': 3, 'симона': 107, 'герц': 18, 'simone': 1, 'giertz': 0, 'прославившаяся': 91, 'необычными': 67, 'изобретениями': 42, 'перенесла': 83, 'операцию': 78, 'об': 72, 'этом': 129, 'рассказали': 96, 'ее': 33, 'представители': 89, 'в': 12, 'twitter': 2, 'еще': 35, 'конце': 47, 'апреля': 5, 'девушка': 24, 'сообщила': 109, 'подписчикам': 85, 'о': 71, 'недуге': 65, 'оказалось': 76, 'что': 125, 'у': 118, 'нее': 66, 'мозге': 55, 'обнаружили': 73, 'доброкачественную': 29, 'опухоль': 79, 'размером': 95, 'с': 100, 'мяч': 57, 'для': 28, 'гольфа': 21, 'блогер': 7, 'даже': 22, 'дала': 23, 'ей': 34, 'имя': 43, 'назвав': 60, 'новообразование': 70, 'брайаном': 9, 'сильно': 106, 'переживала': 82, 'перед': 81, 'хирургическим': 121, 'вмешательством': 14, 'одном': 75, 'из': 38, 'предоперационных': 88, 'видео': 13, 'она': 77, 'говорила': 19, 'очень': 80, 'напугана': 64, 'однако': 74, 'врачи': 15, 'быстро': 11, 'удалили': 119, 'и': 37, 'спасли': 110, 'девушке': 25, 'жизнь'

Помимо этого, CountVectorizer умеет выделять n-граммы:

In [27]:
# ngram_range - это кортеж, который указывает длины последовательсностей, которые надо выделить. 
# Обязательны оба значения. Если хочется извлечь 4-граммы, надо передать (4,4).
counter=CountVectorizer(ngram_range=(1,2), token_pattern=r'[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+')
res=counter.fit_transform([news.News.iloc[0]])
print(counter.vocabulary_)

{'шведская': 279, 'youtube-знаменитость': 7, 'симона': 236, 'герц': 43, 'simone': 2, 'giertz': 0, 'прославившаяся': 203, 'необычными': 152, 'изобретениями': 102, 'перенесла': 187, 'операцию': 175, 'об': 162, 'этом': 283, 'рассказали': 213, 'ее': 78, 'представители': 199, 'в': 25, 'twitter': 4, 'еще': 85, 'конце': 112, 'апреля': 11, 'девушка': 58, 'сообщила': 241, 'подписчикам': 191, 'о': 160, 'недуге': 148, 'оказалось': 170, 'что': 273, 'у': 259, 'нее': 150, 'мозге': 128, 'обнаружили': 164, 'доброкачественную': 70, 'опухоль': 177, 'размером': 211, 'с': 221, 'мяч': 132, 'для': 67, 'гольфа': 52, 'блогер': 15, 'даже': 54, 'дала': 56, 'ей': 83, 'имя': 104, 'назвав': 138, 'новообразование': 158, 'брайаном': 19, 'сильно': 234, 'переживала': 185, 'перед': 183, 'хирургическим': 265, 'вмешательством': 33, 'одном': 168, 'из': 92, 'предоперационных': 197, 'видео': 31, 'она': 172, 'говорила': 48, 'очень': 180, 'напугана': 146, 'однако': 166, 'врачи': 35, 'быстро': 23, 'удалили': 261, 'и': 89, 'спа

Выделим пять самых частотных слов или словосочетаний из текста новости. Воспользуемся тем фактом, что CountVectorizer умеет работать со списками новостей.

In [28]:
def getMostFrequentWords(text):
    counter=CountVectorizer(ngram_range=(1,2), token_pattern=r'[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+')
    res=counter.fit_transform([text])
    frq = sorted([(i, int(res[0][0,i])) for i in range(res[0].shape[1])], key = lambda x: x[1], reverse = True)[:5]
    vocab = {w:res[0,i] for w,i in counter.vocabulary_.items()}
    return [[w for w, n in counter.vocabulary_.items() if n==i][0] for i, f in frq], vocab
    

In [29]:
   
freqwords = []
vocabs = []
for i in tqdm(range(news.shape[0])):
    fw, v = getMostFrequentWords(news.News.iloc[i])
    freqwords.append(fw)
    vocabs.append(v)
    
news['Vocabular'] = vocabs
news['Freq Words'] = freqwords

100%|██████████| 7816/7816 [05:09<00:00, 25.23it/s]


In [30]:
news.head()

Header  ...                           Freq Words
0  «Королева дерьмовых роботов» перенесла операци...  ...               [в, герц, ее, из, что]
1                     У Су-57 нашли «тайные ноу-хау»  ...                  [су, в, не, на, ни]
2                    Знарок лишился еще одного поста  ...         [и, в, знарок, ска, тренера]
3  СК заинтересовался задержанием аутиста московс...  ...                   [в, его, и, к, по]
4  Киевляне перекрыли проспект из-за сбитого поли...  ...  [в, на, автомобиль, в котором, дтп]

[5 rows x 5 columns]

Подключим морфологический анализ, чтобы избавиться от стоп-слов и привести формы слова к лемме. Начнем с Pymorphy.

In [33]:
import pymorphy2

In [34]:
morph=pymorphy2.MorphAnalyzer() # Создает объект морфоанализатора и загружет словарь.
wordform=morph.parse('стекло')  # Проведем анализ слова "стекло"...
print(wordform)                 # ... и посмотрим на результат.

[Parse(word='стекло', tag=OpencorporaTag('NOUN,inan,neut sing,nomn'), normal_form='стекло', score=0.690476, methods_stack=((DictionaryAnalyzer(), 'стекло', 157, 0),)), Parse(word='стекло', tag=OpencorporaTag('NOUN,inan,neut sing,accs'), normal_form='стекло', score=0.285714, methods_stack=((DictionaryAnalyzer(), 'стекло', 157, 3),)), Parse(word='стекло', tag=OpencorporaTag('VERB,perf,intr neut,sing,past,indc'), normal_form='стечь', score=0.023809, methods_stack=((DictionaryAnalyzer(), 'стекло', 1015, 3),))]


In [36]:
wordform=morph.parse('ёрничали') 
wordform

[Parse(word='ёрничали', tag=OpencorporaTag('VERB,impf,intr plur,past,indc'), normal_form='ёрничать', score=1.0, methods_stack=((DictionaryAnalyzer(), 'ёрничали', 15, 10),))]

In [38]:
wordform[0].score

1.0

In [39]:
wordform[0].tag

OpencorporaTag('VERB,impf,intr plur,past,indc')

Самым простым видом борьбы с омонимией является выбор нулевого элемента из списка, возвращенного морфологическим анализом. Такой подход дает около 90% точности при выборе начальной формы и до 80% если мы обращаем внимание на грамматические параметры.<br><br>
Вместо Pymorphy можно использовать PyMystem. Его плюсом является тот факт, что он сам снимает омонимию. Используя функцию lemmatize можно получить набор начальных форм слов. Используя функцию analyze можно получить полную информацию о словах.

In [87]:
import pymystem3 # Еще один морфологический анализатор. При первом запуске грузит словари из Сети.

In [ ]:
mystem=pymystem3.Mystem()
print(mystem.lemmatize('эти типы стали есть в цеху.'))
print(mystem.analyze('эти типы стали есть в цеху.'))

In [ ]:
my_res=mystem.analyze('эти типы стали есть в цеху.')
if 'analysis' in my_res[0].keys():
    print(my_res[0]['analysis'][0]['gr'].split("=")[0])

APRO


Функция `lemmatize` делит текст на слова и знаки препинания, а затем возвращает для них только начальную форму.

Функция `analyze` возвращает не только начальную форму, но и всю информацию о слове, как это делал перед этим Pymorphy. 

Основным отличием является то, что Mystem снимает омонимию. Как видно из примера, делает он это не всегда корректно, но нам не придется думать о том, какой вариант разбора следует взять.

Еще одна библиотека - NLTK. По сравнению с двумя предыдущими библиотеками она обладает более широкой функциональностью и изначально писалась для работы с разными языками.

In [42]:
import nltk # Иностранный морфологический анализатор

Перед началом использования необходимо загрузить необходимые библиотеки или корпуса.

In [44]:
nltk.download() # По дороге будут появляться поле ввода. Грузит всё из Сети.

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.....

True

Можно сразу скачать нужный пакет, если вы знаете, как он назыввается.

In [45]:
nltk.download(['averaged_perceptron_tagger_ru', 'stopwords'])

[nltk_data] Downloading package averaged_perceptron_tagger_ru to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

Функция `word_tokenize` возвращает начальные формы слов. 

Функция `pos_tag` возвращает список начальных форм и их частей речи.

In [50]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [48]:
tokens = nltk.word_tokenize('Эти типы стали есть в цеху') # Токенизация.
bi_tokens = list(nltk.bigrams(tokens))
tokens, bi_tokens

(['Эти', 'типы', 'стали', 'есть', 'в', 'цеху'],
 [('Эти', 'типы'),
  ('типы', 'стали'),
  ('стали', 'есть'),
  ('есть', 'в'),
  ('в', 'цеху')])

In [51]:
pos = nltk.pos_tag(tokens) # Частеречная разметка.
bi_pos = list(nltk.bigrams(pos))
pos, bi_pos


([('Эти', 'JJ'),
  ('типы', 'NNP'),
  ('стали', 'NNP'),
  ('есть', 'NNP'),
  ('в', 'NNP'),
  ('цеху', 'NN')],
 [(('Эти', 'JJ'), ('типы', 'NNP')),
  (('типы', 'NNP'), ('стали', 'NNP')),
  (('стали', 'NNP'), ('есть', 'NNP')),
  (('есть', 'NNP'), ('в', 'NNP')),
  (('в', 'NNP'), ('цеху', 'NN'))])

У NLTK заведен список стоп-слов, которые лучше фильтровать при анализе текстов. Но их не очень много.

In [52]:
# Оставим только те слова, которых нет в списке стоп-слов.
filtered_words = [token for token in tokens if token not in nltk.corpus.stopwords.words('russian')]
print('всего русских стоп-слов', len(nltk.corpus.stopwords.words('russian')))
filtered_words

всего русских стоп-слов 151


['Эти', 'типы', 'стали', 'цеху']

Ту же самую задачу в других библиотеках можно решить при помощи фильтра частей речи. Можно считать, что значимыми являются лишь существительные, прилагательные, глаголы, причастия и деепричастия. Ниже приведены названия частей речи для разных библиотек.
<table>
<tr><th>Часть речи</th><th>Pymorphy</th><th>Mystem</th><th>NLTK</th></tr>
<tr><td>Существительное</td><td>NOUN</td><td>S</td><td>NN</td></tr>
<tr><td>Прилагательное</td><td>ADJF, ADJS</td><td>A</td><td>NNP</td></tr>
<tr><td>Глагол</td><td>VERB</td><td>V</td><td>JJ</td></tr>
<tr><td>Причастие</td><td>PRTF, PRTS</td><td>V</td><td>NNP</td></tr>
<tr><td>Деепричастие</td><td>GRND</td><td>V</td><td>NNP</td></tr>
</table>


Приведем все слова текста к начальным формам при помощи разных библиотек. Прибавим при этом к словам части речи.

In [53]:
# Pymorphy
def normalizePymorphy(text):
    tokens = re.findall('[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+', text)
    words = []
    for t in tokens:
        pv = morph.parse(t)
        words.append(pv[0].normal_form + '_' + str(pv[0].tag.POS)) # Берем наиболее вероятную форму.
    return words    
        
# Обратите внимание, что про иностранные слова словарь ничего не знает.
normalizePymorphy(news.News.iloc[0])

['шведский_ADJF',
 'youtube-знаменитость_NOUN',
 'симона_NOUN',
 'герц_NOUN',
 'simone_None',
 'giertz_None',
 'прославиться_PRTF',
 'необычный_ADJF',
 'изобретение_NOUN',
 'перенести_VERB',
 'операция_NOUN',
 'о_PREP',
 'это_NPRO',
 'рассказать_VERB',
 'она_NPRO',
 'представитель_NOUN',
 'в_PREP',
 'twitter_None',
 'ещё_ADVB',
 'в_PREP',
 'конец_NOUN',
 'апрель_NOUN',
 'девушка_NOUN',
 'сообщить_VERB',
 'подписчик_NOUN',
 'о_PREP',
 'недуг_NOUN',
 'оказаться_VERB',
 'что_CONJ',
 'у_PREP',
 'она_NPRO',
 'в_PREP',
 'мозг_NOUN',
 'обнаружить_VERB',
 'доброкачественный_ADJF',
 'опухоль_NOUN',
 'размер_NOUN',
 'с_PREP',
 'мяч_NOUN',
 'для_PREP',
 'гольф_NOUN',
 'блогер_NOUN',
 'даже_PRCL',
 'дать_VERB',
 'она_NPRO',
 'имя_NOUN',
 'назвать_GRND',
 'новообразование_NOUN',
 'брайан_NOUN',
 'герц_NOUN',
 'сильно_ADVB',
 'переживать_VERB',
 'перед_PREP',
 'хирургический_ADJF',
 'вмешательство_NOUN',
 'в_PREP',
 'один_ADJF',
 'из_PREP',
 'предоперационный_ADJF',
 'видео_NOUN',
 'она_NPRO',
 'гов

In [ ]:
# PyMystem
def normalizePymystem(text):
    tokens = mystem.analyze(text)
    words = []
    for t in tokens:
        if 'analysis' in t.keys():
            if t['analysis'] != []:
                words.append(t['analysis'][0]['lex']+'_'+t['analysis'][0]['gr'][0])
            else:
                words.append(t['text']+'_'+'U')
    return words    
        
# Не все считают, что причастие всегда выступает в роли глагола, но иногда так значительно проще.
normalizePymystem(news.News.iloc[0])

['шведский_A',
 'YouTube_U',
 'знаменитость_S',
 'симона_S',
 'герц_S',
 'Simone_U',
 'Giertz_U',
 'прославляться_V',
 'необычный_A',
 'изобретение_S',
 'перенести_V',
 'операция_S',
 'об_P',
 'это_S',
 'рассказывать_V',
 'она_S',
 'представитель_S',
 'в_P',
 'Twitter_U',
 'еще_A',
 'в_P',
 'конец_S',
 'апрель_S',
 'девушка_S',
 'сообщать_V',
 'подписчик_S',
 'о_P',
 'недуг_S',
 'оказываться_V',
 'что_C',
 'у_P',
 'она_S',
 'в_P',
 'мозг_S',
 'обнаруживать_V',
 'доброкачественный_A',
 'опухоль_S',
 'размер_S',
 'с_P',
 'мяч_S',
 'для_P',
 'гольф_S',
 'блогер_S',
 'даже_C',
 'давать_V',
 'она_S',
 'имя_S',
 'называть_V',
 'новообразование_S',
 'брайан_S',
 'герц_S',
 'сильно_A',
 'переживать_V',
 'перед_P',
 'хирургический_A',
 'вмешательство_S',
 'в_P',
 'один_A',
 'из_P',
 'предоперационный_A',
 'видео_S',
 'она_S',
 'говорить_V',
 'что_C',
 'очень_A',
 'напугать_V',
 'однако_C',
 'врач_S',
 'быстро_A',
 'удалять_V',
 'опухоль_S',
 'и_C',
 'спасать_V',
 'девушка_S',
 'жизнь_S',
 'симо

In [54]:
# NLTK
def normalizeNLTK(text):
    tokens = nltk.pos_tag(nltk.word_tokenize(text))
    words = []
    for t in tokens:
        if t[0] != t[1]:
            words.append(t[0]+'_'+t[1])
    return words    
        
# А вот здесь с частеречной разметкой всё плохо, а параметров нет вовсе.
normalizeNLTK(news.News.iloc[0])

['Шведская_JJ',
 'YouTube-знаменитость_NNP',
 'Симона_NNP',
 'Герц_NNP',
 'Simone_NNP',
 'Giertz_NNP',
 'прославившаяся_JJ',
 'необычными_NNP',
 'изобретениями_NNP',
 'перенесла_NNP',
 'операцию_NNP',
 'Об_VB',
 'этом_JJ',
 'рассказали_NNP',
 'ее_NNP',
 'представители_NNP',
 'в_NNP',
 'Twitter_NNP',
 'Еще_VB',
 'в_JJ',
 'конце_NNP',
 'апреля_NNP',
 'девушка_NNP',
 'сообщила_NNP',
 'подписчикам_NNP',
 'о_NNP',
 'недуге_NNP',
 'Оказалось_NN',
 'что_NNP',
 'у_NNP',
 'нее_NNP',
 'в_NNP',
 'мозге_NNP',
 'обнаружили_NNP',
 'доброкачественную_NNP',
 'опухоль_NNP',
 'размером_NNP',
 'с_NNP',
 'мяч_NNP',
 'для_NNP',
 'гольфа_NNP',
 'Блогер_VB',
 'даже_JJ',
 'дала_NNP',
 'ей_NNP',
 'имя_NNP',
 'назвав_NNP',
 'новообразование_NNP',
 'Брайаном_NNP',
 'Герц_VB',
 'сильно_JJ',
 'переживала_NNP',
 'перед_NNP',
 'хирургическим_NNP',
 'вмешательством_NNP',
 'В_VB',
 'одном_JJ',
 'из_NNP',
 'предоперационных_NNP',
 'видео_NNP',
 'она_NNP',
 'говорила_NNP',
 'что_NNP',
 'очень_NNP',
 'напугана_NNP',
 'Од

In [55]:
imp_POS = ['ADJF', 'ADJS', 'NOUN', 'VERB', 'PRTF', 'PRTS', 'GRND']

def getMostFrequentWordsFiltered(text):
    
    tokens = re.findall('[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+', text)
    words = []
    for t in tokens:
        pv = morph.parse(t)
        if pv[0].tag.POS in imp_POS and pv[0].normal_form != 'быть':
            words.append(pv[0].normal_form)
    text = ' '.join(words)
    
    counter=CountVectorizer(ngram_range=(1,2), token_pattern=r'[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+')
    res=counter.fit_transform([text])
    frq = sorted([(i, int(res[0][0,i])) for i in range(res[0].shape[1])], key = lambda x: x[1], reverse = True)[:5]
    vocab = {w:res[0,i] for w,i in counter.vocabulary_.items()}
    return [[w for w, n in counter.vocabulary_.items() if n==i][0] for i, f in frq], vocab

Теперь посмотрим какие слова оказываются наиболее частотными, если выкинуть "лишние".

Не забывайте, что в некоторых задачах эти слова, а также формы слова, могут оказаться нужными и важными.

In [56]:
freqwords = []
vocabs = []
for i in tqdm(range(news.shape[0])):
    fw, v = getMostFrequentWordsFiltered(news.News.iloc[i])
    freqwords.append(fw)
    vocabs.append(v)
    
news['Vocabular'] = vocabs
news['Freq Words'] = freqwords

100%|██████████| 7816/7816 [09:21<00:00, 13.92it/s]


In [58]:
news.head()

Header  ...                                         Freq Words
0  «Королева дерьмовых роботов» перенесла операци...  ...        [герц, девушка, врач, изобретение, опухоль]
1                     У Су-57 нашли «тайные ноу-хау»  ...     [су, лётчик-испытатель, который, мир, толбоев]
2                    Знарок лишился еще одного поста  ...             [тренер, знарка, команда, ска, апрель]
3  СК заинтересовался задержанием аутиста московс...  ...  [человек, задержать, иванов, молодой, молодой ...
4  Киевляне перекрыли проспект из-за сбитого поли...  ...           [который, автомобиль, дтп, киев, кортеж]

[5 rows x 5 columns]

Теперь попробуем другой показатель для подсчета важности слов в тексте - $TF*IDF$. Здесь $TF$ - Term Frequency, частота термина в документе, а $IDF$ - Inverted Document Frequency, обратная частота термина в коллекции (количество документов, в которых встречается данный термин).

Идея метрики очень проста. Если слово встречается почти во всех документах - его различительная сила очень мала и само слово не является важным. Если слово часто встречается в данном документе, то оно являетсяя важным для него.

[Иллюстрация](https://livebook.manning.com/book/natural-language-processing-in-action/chapter-4/v-4/61)

Метрика считается на коллекции документов для каждого слова, каждого документа. Для расчета меры можно использовать `TfidfVectorizer`, который работает так же как `CountVectorizer`.

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

Изменим функцию, чтобы она не возвращала часть речи. Посмотрим как TF*IDF поступает со стоп-словами.

In [60]:
def normalizePymorphy2(text):
    tokens = re.findall('[A-Za-zА-Яа-яЁё]+\-[A-Za-zА-Яа-яЁё]+|[A-Za-zА-Яа-яЁё]+', text)
    words = []
    for t in tokens:
        pv = morph.parse(t)
        words.append(pv[0].normal_form)
    return words    

Посчитаем наиболее важные по TF*IDF слова и пары слов.

In [83]:
tfCounter=TfidfVectorizer(ngram_range=(1,2), token_pattern=r'[А-Яа-яЁё]+\-[А-Яа-яЁё]+|[А-Яа-яЁё]+')
tfres=tfCounter.fit_transform([' '.join(normalizePymorphy2(n)) for n in news.News] )

Посчитаем пять самых важных слов по TF*IDF для каждой статьи.

In [84]:
freqwords = []
for i in tqdm(range(news.shape[0])):

    tfs = [(k,tfres[i][0, tfCounter.vocabulary_.get(k)]) for k in news.Vocabular.iloc[i] 
         if k in tfCounter.vocabulary_.keys()]
    fw = [w for w, f in sorted(tfs, key = lambda x: x[1], reverse = True)[:5]]
    freqwords.append(fw)
    
news['Freq Words TFIDF'] = freqwords

100%|██████████| 7816/7816 [02:32<00:00, 51.15it/s]


In [85]:
news.head()

Header  ...                                   Freq Words TFIDF
0  «Королева дерьмовых роботов» перенесла операци...  ...  [герц, симона, изобретение, прославиться, опух...
1                     У Су-57 нашли «тайные ноу-хау»  ...  [су, лётчик-испытатель, толбоев, кнышов, ноу-хау]
2                    Знарок лишился еще одного поста  ...            [знарка, ска, тренер, знарк, хоккейный]
3  СК заинтересовался задержанием аутиста московс...  ...  [иванов, отделение, молодой человек, аутист, з...
4  Киевляне перекрыли проспект из-за сбитого поли...  ...        [кортеж, дтп, сбить, порошенко, григоренко]

[5 rows x 6 columns]

### Классификация текстов

Попробуем на тех же новостях построить классификатор, отличающий новости про футбол от новостей про истребители.

Для начала сформируем выборки новостей по этим темам. Истребители выделим по ключевым словам " Су-" и "МиГ", футбол - по ключевому слову "футбол".

In [63]:
news_air = news[news.News.str.contains(" Су-|МиГ")]

In [64]:
news_air.head()

Header  ...                                         Freq Words
1                       У Су-57 нашли «тайные ноу-хау»  ...     [су, лётчик-испытатель, который, мир, толбоев]
81           Полет МиГ-31 в стратосфере попал на видео  ...  [полёт, авиация, боевой, воскресенский, выполн...
124  Раскрыто вероятное имя пропавшего в Афганистан...  ...     [афганистан, год, пропасть, советский, лётчик]
171  Раскрыты неизвестные факты из биографии бывшег...  ...       [руцкой, советский, афганистан, лётчик, год]
182  Су-25 пролетел в десяти метрах над украинским ...  ...  [азовский, азовский море, море, пограничник, у...

[5 rows x 5 columns]

In [65]:
news_football = news[news.News.str.contains("футбол")]

In [66]:
news_football.head()

Header  ...                                         Freq Words
3   СК заинтересовался задержанием аутиста московс...  ...  [человек, задержать, иванов, молодой, молодой ...
19             Уткин обозвал Черчесова медной статуей  ...  [сборная, россия, сборная россия, австрия, ком...
27  Капитана «Реала» завалили угрозами за травму С...  ...   [рамос, английский, защитник, звонок, ливерпуль]
30  Ученые назвали победителя ЧМ-2018 и предрекли ...  ...         [процент, победа, чемпионат, команда, мир]
42  Никита Михалков объяснил происхождение своих б...  ...            [год, миллион, михалков, мой, режиссёр]

[5 rows x 5 columns]

In [67]:
news_air.shape, news_football.shape, news.shape

((71, 5), (1018, 5), (7816, 5))

Выборки не сбланансированные - 1:10, нас ждут серьезные проблемы. Можно было бы сбалансировать за счет добавления новостей про авиацию вообще и жесткому отсеиванию футбола (скажем, оставить только новости в которых "футбол" и "клуб" встречается чаще всего; или оставить информацию об играх), но так интересней.

Возьмем 60 новостей про истребители и 1000 про футбол, нормализуем их, посчитаем TF*IDF.

In [68]:
import numpy as np

In [69]:
train_size_air = 60
train_size_football = 1000

In [70]:
news_train_X = np.array([' '.join(normalizePymorphy2(n)) for n in news_air.News[:train_size_air]])
news_train_Y = np.zeros(train_size_air)
news_train_X = np.concatenate([news_train_X, np.array([' '.join(normalizePymorphy2(n)) for n in news_football.News[:train_size_football]])])
news_train_Y = np.concatenate([news_train_Y, np.ones(train_size_football)])

In [71]:
news_test_X = np.array([' '.join(normalizePymorphy2(n)) for n in news_air.News[train_size_air:]])
news_test_Y = np.zeros(news_air.shape[0] - train_size_air)
news_test_X = np.concatenate([news_test_X, np.array([' '.join(normalizePymorphy2(n)) for n in news_football.News[train_size_football:]])])
news_test_Y = np.concatenate([news_test_Y, np.ones(news_football.shape[0] - train_size_football)])

In [72]:
tfCounter=TfidfVectorizer(ngram_range=(1,2), token_pattern=r'[А-Яа-яЁё]+\-[А-Яа-яЁё]+|[А-Яа-яЁё]+')
train_tf_X=tfCounter.fit_transform(news_train_X)
test_tf_X=tfCounter.transform(news_test_X)

На сумме можно посмотреть, что новости про истребители содержат в себе гораздо меньше слов. Основное разнообразие словарю добавляет футбольная тематика. Можно серьезно сократить размер пространства за счет удаления редких слов, но тоже не сейчас.

In [73]:
np.sum(train_tf_X[:60], axis=0), np.sum(train_tf_X[60:], axis=0)

(matrix([[0.91439206, 0.        , 0.        , ..., 0.        , 0.        ,
          0.        ]]),
 matrix([[8.64296831, 0.06857061, 0.0754369 , ..., 0.06335132, 0.03088415,
          0.03088415]]))

Попробуем на этой задаче логистическую регрессию, так как она может выдавать вероятности принадлежности классам. Так как мы ждем проблемы, эта информация может нам понадобиться.

In [74]:
from sklearn.linear_model import LogisticRegression

In [75]:
# Берем логистическую регрессию с настройками по умолчанию.
logreg = LogisticRegression()
# Настраиваем ее на тренировочную выборку.
logreg.fit(train_tf_X, news_train_Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [76]:
# Предсказываем результат на тестовой выборке.
test_Y_hat = logreg.predict_proba(test_tf_X)

In [77]:
# Результат посмотрим глазами.
list(zip(test_Y_hat, news_test_Y))

[(array([0.28613766, 0.71386234]), 0.0),
 (array([0.18893669, 0.81106331]), 0.0),
 (array([0.21797376, 0.78202624]), 0.0),
 (array([0.26702931, 0.73297069]), 0.0),
 (array([0.12671463, 0.87328537]), 0.0),
 (array([0.21754966, 0.78245034]), 0.0),
 (array([0.48896353, 0.51103647]), 0.0),
 (array([0.41647457, 0.58352543]), 0.0),
 (array([0.36164916, 0.63835084]), 0.0),
 (array([0.24866701, 0.75133299]), 0.0),
 (array([0.28608782, 0.71391218]), 0.0),
 (array([0.04434754, 0.95565246]), 1.0),
 (array([0.03125959, 0.96874041]), 1.0),
 (array([0.02785101, 0.97214899]), 1.0),
 (array([0.03433852, 0.96566148]), 1.0),
 (array([0.03980162, 0.96019838]), 1.0),
 (array([0.04437876, 0.95562124]), 1.0),
 (array([0.04272087, 0.95727913]), 1.0),
 (array([0.03525889, 0.96474111]), 1.0),
 (array([0.04662555, 0.95337445]), 1.0),
 (array([0.03408479, 0.96591521]), 1.0),
 (array([0.0308865, 0.9691135]), 1.0),
 (array([0.03483388, 0.96516612]), 1.0),
 (array([0.04642846, 0.95357154]), 1.0),
 (array([0.0387755

Почти нигде вероятность нулевого класса не выше вероятности первого. Зато, хорошо видно, что первый класс там, где вероятность первого класса выше 0,95 или вероятность нулевого - выше 0.1. Попробуем сыграть на этом. Проверим на первых ста новостях, хорошо ли они разделяются.

In [78]:
all_news_X = np.array([' '.join(normalizePymorphy2(n)) for n in news.News[:100]])
all_tf_X=tfCounter.transform(all_news_X)
all_Y_hat = logreg.predict_proba(all_tf_X)

In [79]:
all_Y_hat[:10]

array([[0.052423  , 0.947577  ],
       [0.36467998, 0.63532002],
       [0.03777473, 0.96222527],
       [0.04974062, 0.95025938],
       [0.05312288, 0.94687712],
       [0.04891462, 0.95108538],
       [0.05035109, 0.94964891],
       [0.05716486, 0.94283514],
       [0.05771737, 0.94228263],
       [0.07017849, 0.92982151]])

In [80]:
news.Header[:100][all_Y_hat[:,0]>0.1]

1                        У Су-57 нашли «тайные ноу-хау»
56    Российские истребители проигнорировали турок и...
65    Сбитого 30 лет назад советского летчика нашли ...
66                            «Центр Хруничева» усохнет
81            Полет МиГ-31 в стратосфере попал на видео
86    Раскрыто вероятное местонахождение сбитого во ...
99    Производитель РД-180 признал отставание России...
Name: Header, dtype: object

In [81]:
news.Header[:100][all_Y_hat[:,1]>0.95]

2                       Знарок лишился еще одного поста
3     СК заинтересовался задержанием аутиста московс...
5      Российская легкоатлетка одержала 40 побед подряд
11    Гонконгских геев полечили молитвами и отказом ...
19               Уткин обозвал Черчесова медной статуей
22    Школьника отказались пускать в автобус из-за н...
24    Елена Темникова рассказала об эксплуатации сек...
27    Капитана «Реала» завалили угрозами за травму С...
29    Депутат заказал бизнесмена и расплатился с раз...
30    Ученые назвали победителя ЧМ-2018 и предрекли ...
33           Девушек в купальниках перестали фотошопить
36    Британец заглянул под кровать и испытал радост...
37    Проваливший чемпионат мира по хоккею тренер пр...
38           В Канаде повадились угонять гоночные ванны
44    Глава московского СК Дрыманов подтвердил свой ...
46                   Зидан покинул «Реал» из-за Роналду
52          Ubisoft анонсировала новый Assassin’s Creed
53      Россияне забастовали после скачка цен на

In [82]:
news.Header[:100][(all_Y_hat[:,1]<0.95)&(all_Y_hat[:,0]<0.1)]

0     «Королева дерьмовых роботов» перенесла операци...
4     Киевляне перекрыли проспект из-за сбитого поли...
6             В Google обнаружили «самый странный» сбой
7               Ким Чен Ын предложил Путину встретиться
8             Британка скатилась с горы и осталась жива
                            ...                        
93    Воробьев осмотрел новый терминал аэропорта Шер...
95    Выступления фестиваля Primavera Sound можно бу...
96            На Крымском мосту произошла первая авария
97       «Русал» попробуют перевести в российский офшор
98    Найден способ «убить» любой компьютер силой звука
Name: Header, Length: 65, dtype: object